name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm tauri:build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: compresso-windows
          path: src-tauri/target/release/bundle/**
